# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13885def51ab14b63c852a45100f0069da8a6099ed94e010375141c191a9b556b0aad9f9015668505a8687d21da75324adce6f5291ca29344f3f7e72baa2d926

test:
  secret_key_base: 360e4f5b4ec2765211e8e458458dc73f5f21f88647eaf020d7ffd0c02b21ac036912e2358034a109eabebe418d079faf935fca04a6cd3880d5006c97ed13e0f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
